### ISSUE TITLE
CaptureInterface.DisplayInGameText not working, cannot add overlay from program.

### ISSUE THREAD

**Issue by HACKHERS** [spazzarama/Direct3DHook#36] opened 2015-11-19 22:47 UTC
I tested on "TestScreenshot", It's not sending "Screenshot captured..." text to game. 

And another problem is I cant add (for example image) from CaptureProcess It self, cannot find another way to add too (without changing dll)

I'm using windows 10.
Debug log:
Debug: Autodetect found Direct3D 9
Debug: Autodetect found Direct3D 11
Information: Remote process is a 32-bit process.
Information: Injected into process Id:27212.

**Comment by HACKHERS** [comment] 2015-11-20 16:26
+ I'm not able to move DLL's to /lib/ directory. It looks so messy when every thing in same folder.

**Comment by alexalok** [comment] 2015-12-28 15:19
I can confirm that DisplayInGameText() is not working with DirectX9.
OS: Windows 10 (x64)
Game: Warface (x32)

**Comment by Symbai** [comment] 2016-01-20 07:51
Its because its commented in DXHookD3D11 and DXHookD3D9 but on DX10 its availble. I don't know why this hasn't been fixed, there were new commits after this report.

**Comment by spazzarama** [comment] 2016-01-20 09:23
@Symbai I have been working on a better approach that allows the host app to send through a full overlay to the injected assembly, rather than just text. This is why it hasn't been committed yet.

**Comment by HACKHERS** [comment] 2016-01-21 13:50
@spazzarama, Awesome! cant wait :+1:

**Comment by hamishebahar** [comment] 2017-07-14 15:31
hi,
please test motogp 13, textoverly not working on this game and i dont khnow why?
font.DrawText do not return 0 but i cannot see anything in motogp 13, but another game i tested worked fine.

**Closed** 2018-02-21 05:53 UTC
